In [2]:
import //;P0YY.0 as np
import pandas as pd

In [2]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
constant_array = np.full(10, 3)

In [3]:
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(8, 1.5)

array([1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5])

In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)

In [7]:
array_from_list

array([2, 3, 4])

In [8]:
range_array = np.arange(10)  # Creates an array from 0 to 9

In [9]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
linspace_array = np.linspace(0, 1, 11)  # Creates 11 numbers from 0 to 1

In [5]:
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [3]:
np. random.seed(2)
np. random.rand(3,6)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
        0.33033482],
       [0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
        0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515, 0.85397529,
        0.49423684]])

In [3]:
u = np.array([2, 4, 3, 1])
v = np.array([1, 3, 2, 4])

In [8]:
U.shape

(3, 4)

In [4]:
U = np.array ([
    [2, 4, 5, 6],
    [1, 2, 1, 3],
    [3, 2, 1, 1],
])

In [11]:
v = np.array ([2, 0.5, 1])

In [9]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] + v[i]
    
    return result

In [10]:
vector_vector_multiplication(u, v)

20.0

In [4]:
V =  np.array ([
    [2, 4, 3],
    [1, 2, 1],
    [3, 2, 1],
    [2, 1, 0],
])

In [12]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [5]:
v.shape

(4,)

In [13]:
matrix_vector_multiplication(U, v)

array([27., 17., 17.])

In [30]:
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv('/home/auto/mlzoomcamp/laptops.csv')

In [15]:
df.Brand.describe()

count     2160
unique      27
top       Asus
freq       415
Name: Brand, dtype: object

In [14]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [24]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [23]:
df[
    df['Brand'] == 'Dell' 
]

Laptop       Status Brand  \
161   Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...          New  Dell   
271   Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...          New  Dell   
281   Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...          New  Dell   
319   Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...          New  Dell   
328   Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...          New  Dell   
...                                                 ...          ...   ...   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
1844  Dell Vostro 5301 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1845  Dell Vostro 5502 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1846  Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512G...  Refurbished  Dell   
1847  Dell XPS 7390 Intel Core i7-10510U/16GB/512GB ...  Refurbished  Dell   

         Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
161     Vostro  Intel Core i3    8      256          SSD  NaN    15.6    No   
271     Vostro  Intel Core i5    8      256          SSD  NaN    15.6    No   
281     Vostro  Intel Core i7   16      512          SSD  NaN    15.6    No   
319   Latitude  Intel Core i5    8      256          SSD  NaN    15.6    No   
328     Vostro  Intel Core i5   16      512          SSD  NaN    15.6    No   
...        ...            ...  ...      ...          ...  ...     ...   ...   
1843    Vostro  Intel Core i5    8      256          SSD  NaN    13.3    No   
1844    Vostro  Intel Core i5    8      512          SSD  NaN    13.3    No   
1845    Vostro  Intel Core i5    8      512          SSD  NaN    15.6    No   
1846       XPS  Intel Core i5    8      512          SSD  NaN    13.4    No   
1847       XPS  Intel Core i7   16      512          SSD  NaN    13.3    No   

      Final Price  
161        599.00  
271        690.15  
281        889.00  
319        789.00  
328        869.00  
...           ...  
1843       420.74  
1844       511.59  
1845       549.93  
1846       699.00  
1847      1086.88  

[84 rows x 12 columns]

In [24]:
df['Final Price'].max()

7150.47

In [27]:
dell = df[
    df['Brand'] == 'Dell' 
]

In [29]:
dell_max_price = print(dell['Final Price'].max())

3936.0


In [37]:
df['Screen'].median()

15.6